baseURL: https://www.intapartments.com
languageCode: en-us
title: Hugo Fresh Theme
theme: hugo-fresh

params:
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: logos/logo.png
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  mailChimpURL: "https://intapartments.us4.list-manage.com/subscribe/post?u=9aa01c8d9a61e0a6b06dd03b9&amp;id=e4d1e17926"
  hero:
    # Main hero title
    title: Living. Made easy.
    # Hero subtitle (optional)
    subtitle: Want to only see flats that suit you? Tired of all the paperwork, over and over? So are we. Join the waitlist to be updated when we are ready to launch.
    # Button text
    buttontext: Join Waitlist
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  footer:
    # Logo (from /images/logos/___)
    logo: logo-alt.png
  # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://instagram.com/intapartments
      icon: instagram

     
    bulmalogo: false